using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace ADO.NET_Data
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            questionsTableAdapter1.Fill(dB_EFCF_DXApplication_Exercise_04DataSet1.Questions);
            gridControl1.DataSource = questionsBindingSource;
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            //questionsTableAdapter1.Adapter.Update(dB_EFCF_DXApplication_Exercise_04DataSet1);
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        Dictionary<int, decimal> CoustomTotal = new Dictionary<int, decimal>();
        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            int index = e.ListSourceRowIndex;
            decimal answer = Convert.ToDecimal(gridView1.GetListSourceRowCellValue(index, "Answer"));
            decimal code = Convert.ToDecimal(gridView1.GetListSourceRowCellValue(index, "Code"));
            if (e.Column.FieldName != "Result")
            {
                return;
            }

            if (e.IsGetData)
            {
                if (!CoustomTotal.ContainsKey(index))
                {
                    CoustomTotal.Add(index, answer * code);
                }
            }
            else if (e.IsSetData)
            {
                CoustomTotal[index] = Convert.ToDecimal(e.Value);

            }
            e.Value = CoustomTotal[index];
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_EFCF_DXApplication_Exercise_04DataSet11.Histors' table. You can move, or remove it, as needed.
            //this.historsTableAdapter.Fill(this.dB_EFCF_DXApplication_Exercise_04DataSet11.Histors);

        }
    }
}
