using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Working_with_Columns_In_Code
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_EFCF_DXApplication_Exercise_04DataSet.Questions' table. You can move, or remove it, as needed.
            this.questionsTableAdapter.Fill(this.dB_EFCF_DXApplication_Exercise_04DataSet.Questions);
            // TODO: This line of code loads data into the 'dB_EFCF_DXApplication_Exercise_04DataSet1.Questions' table. You can move, or remove it, as needed.
            //this.questionsTableAdapter.Fill(this.dB_EFCF_DXApplication_Exercise_04DataSet1.Questions);
            gridControl1.DataSource = questionsBindingSource;
        }
    }
}
